# Code that calls other functions to generate observed data
# all parameter values generated by 'setParams.R'


genDataFunctions <- function(
  dim = NULL,
  lambda = NULL,
  env.beta = NULL,
  seed = NULL,
  kappa = NULL,
  sigma2x = NULL,
  strata = NULL,
  rows = NULL,
  cols = NULL,
  probs = NULL,
  nsamp = NULL,
  plot = TRUE,
  plotdat = TRUE,
  qsize = NULL,
  rho = NULL,
  correlated = NULL
){

## 'truth' data generation 

source("genData.R")

dat1 <- genData(dim = dim, lambda = lambda, env.beta = env.beta, seed = seed, kappa = kappa, sigma2x = sigma2x)

######## PREPARATION #########

##sampling bias
source('Generate strata levels Lam.R')

#generate a stratification to use for sampling bias
strata1 <- genStrataLam(dat1$Lam, strata = strata, rows = rows, cols = cols)


source("addSpatialBias.R")

#spatial bias not correlated with environmental covariate by default
biasfield <- addSpatialBias(strata1, maxprob = probs[1], correlated = correlated, rho = rho)


#make spatial bias covariate
biascov <- xtabs(covariate ~ y + x, data = biasfield)



####### UNSTRUCTURED DATA ##########

##thinning

source("thinData.R")

#thin data according to biasfield
thin1 <- thinData(dat1, biasfield)

#add env covariate
thin1$env <- dat1$gridcov[as.matrix(thin1[,2:1])]

#add bias covariate
thin1$bias <- biascov[as.matrix(thin1[,2:1])]


#use thinned data as the unstructured data sample
unstructured_data <- thin1


####### STRUCTURED DATA ##########

# Set up structured sample, depends on number of samples and quadrat size

source("sampleStructured.R")

structured_data <- sampleStructured(dat1, biasfield, nsamp = nsamp, plotdat = plotdat, qsize = qsize)
  
return(list(structured_data = structured_data, unstructured_data = unstructured_data, biasfield = biasfield, dat1 = dat1, biascov = biascov, strata1 = strata1))
}



